name: Test
on:
  push:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm test
      - name: Archive Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
